<?php return array(
'cfg_webname'=>'FAENZA',
'cfg_weburl'=>'www.xiutub.com',
'cfg_webpath'=>'/',
'cfg_keyword'=>'FAENZA',
'cfg_description'=>'this is FAENZA',
'cfg_copyright'=>'©2016 FAENZA Sanitary ware All Rights Reserved.',
'cfg_upload_img_type'=>'gif|png|jpg|bmp',
'cfg_upload_soft_type'=>'zip|gz|rar|iso|doc|docx|xls|xlsx|ppt|wps|txt',
'cfg_upload_media_type'=>'swf|flv|mpg|mp3|rm|rmvb|wmv|wma|wav',
'cfg_max_file_size'=>'2097152',
'cfg_imgresize'=>'Y',
'cfg_mb_open'=>'Y',
'cfg_mb_disable'=>'',
'cfg_mb_allowreg'=>'Y',
'cfg_feedbackcheck'=>'Y',
'cfg_replacestr'=>'',
'cfg_feedback_time'=>'',
'cfg_beianhao'=>'©2016 FAENZA Sanitary ware All Rights Reserved.',
'cfg_mobile'=>'15814083660',
'cfg_tel'=>'86-0755-29580912',
'cfg_fax'=>'86-0755-29580631',
'cfg_facaddress'=>'',
'cfg_comaddress'=>'',
)?>